'''
Configuration file for ACNBkg.scripts
'''
import os

USER = os.environ.get('USERNAME')

DIR = os.path.dirname(os.path.realpath(__file__))
# DIR = '/media/andrea/DISK4T1/ACD LAT Adelfio/'

# Folders: parent (data), children (solar, spacecraft, LAT_ACD/output runs)
DATA_FOLDER_NAME = os.path.join(DIR, 'data')
SOLAR_FOLDER_NAME = os.path.join(DATA_FOLDER_NAME, 'solar')
SC_FOLDER_NAME = os.path.join(DATA_FOLDER_NAME, 'spacecraft')
DATA_LATACD_FOLDER_PATH = os.path.join(DATA_FOLDER_NAME, 'LAT_ACD/merged output runs')
MODEL_NN_FOLDER_NAME = os.path.join(DATA_FOLDER_NAME, 'model_nn')

SC_LAT_WEEKLY_FILENAME = 'lat_weekly_spacecraft_merged.fits'
SC_LAT_WEEKLY_FILE_PATH = os.path.join(SC_FOLDER_NAME, SC_LAT_WEEKLY_FILENAME)

SOLAR_FILENAME = 'solar_activity'
SOLAR_FILE_PATH = os.path.join(SOLAR_FOLDER_NAME, SOLAR_FILENAME)

TILE_SIGNAL_FILENAME = 'tile_signal'
TILE_SIGNAL_FILE_PATH = os.path.join(DATA_LATACD_FOLDER_PATH, TILE_SIGNAL_FILENAME)

SC_FILENAME = 'sc'
SC_FILE_PATH = os.path.join(SC_FOLDER_NAME, SC_FILENAME)

INPUTS_OUTPUTS_FILENAME = 'inputs_outputs'
INPUTS_OUTPUTS_FILE_PATH = os.path.join(DATA_FOLDER_NAME, INPUTS_OUTPUTS_FILENAME)

SC_FOLDER_NAME_FROM_LAT_WEEKLY = 'data/spacecraft/LAT/weekly'
SC_FOLDER_NAME_FROM_LAT_WEEKLY = os.path.join(DIR, SC_FOLDER_NAME_FROM_LAT_WEEKLY)
SC_FILENAMES_FROM_LAT_WEEKLY = os.listdir(SC_FOLDER_NAME_FROM_LAT_WEEKLY)
SC_FILE_REL_PATHS_FROM_LAT_WEEKLY = []
SC_FILE_PATHS_FROM_LAT_WEEKLY = []
for SC_FILENAME_FROM_LAT_WEEKLY in SC_FILENAMES_FROM_LAT_WEEKLY:
    SC_FILE_REL_PATH_FROM_LAT_WEEKLY = os.path.join(DIR, SC_FOLDER_NAME_FROM_LAT_WEEKLY, SC_FILENAME_FROM_LAT_WEEKLY)
    SC_FILE_REL_PATHS_FROM_LAT_WEEKLY.append(SC_FILE_REL_PATH_FROM_LAT_WEEKLY)
    SC_FILE_PATHS_FROM_LAT_WEEKLY.append(os.path.join(DIR, SC_FILE_REL_PATH_FROM_LAT_WEEKLY))


def regenerate_lat_weekly():
    SC_FILENAMES_FROM_LAT_WEEKLY = os.listdir(SC_FOLDER_NAME_FROM_LAT_WEEKLY)
    SC_FILE_PATHS_FROM_LAT_WEEKLY = []
    for SC_FILENAME_FROM_LAT_WEEKLY in SC_FILENAMES_FROM_LAT_WEEKLY:
        SC_FILE_REL_PATH_FROM_LAT_WEEKLY = os.path.join(DIR, SC_FOLDER_NAME_FROM_LAT_WEEKLY, SC_FILENAME_FROM_LAT_WEEKLY)
        SC_FILE_PATHS_FROM_LAT_WEEKLY.append(os.path.join(DIR, SC_FILE_REL_PATH_FROM_LAT_WEEKLY))
    return SC_FILE_PATHS_FROM_LAT_WEEKLY

LOGGING_FOLDER_NAME = 'logs'
LOGGING_FILE_NAME = 'acdbkg.log'
LOGGING_FILE_REL_PATH = os.path.join(LOGGING_FOLDER_NAME, LOGGING_FILE_NAME)
LOGGING_FILE_PATH = os.path.join(os.getcwd(), LOGGING_FILE_REL_PATH)

MODEL_NN_SAVED_FILE_NAME = 'saved_model.keras'